# Sections content configuration file
## 
### use navigation.yml file to re-order, delete or add section of each card
### here you can find all content in all pre-build sections

### About [ about ]
about:
  title: "About Me"
  text: "
        <p>
          <strong>Hello! I’m Ayush Garg.</strong></br>A Software Developer based in Bangalore, India. With over 5 years of experience in development, I have honed my skills in understanding client requirements and delivering high-quality solutions. I have worked extensively on products for Enterprise, Distributed, Realtime, and Batching Systems, which has deepened my understanding of Engineering and Design. </br>I possess strong technical and design skills with expertise in Python, Java, React, and more. Additionally, I have a solid grasp of DevOps, enabling me to take projects from development to live deployment seamlessly. My comprehensive skill set ensures that I can deliver efficient, scalable, and robust solutions for any challenge.
        </p>
        "
  list:
    - label: "Age"
      value: "27"

    - label: "Residence"
      value: "Bangalore, India"

    - label: "Open To Work"
      value: "Yes"

    - label: "Location Preference"
      value: "Bangalore, Hydrabad, Pune, Indore"

### Services [ services ]
services:
  title: "My Expertise"
  items:
    - icon: "code"
      name: "Software Development"
      text: "End-to-end solutions combining front-end and back-end"
      h_line: 1

    - icon: "code"
      name: "Cloud and DevOps"
      text: "Build/migrate apps on AWS, Azure, or Google Cloud. Automate deployment with Jenkins, GitHub Actions, or GitLab CI. Docker/Kubernetes for scalable solutions. "
      h_line: 1

    - icon: "code"
      name: "APIs & Integrations"
      text: "Develop and document APIs. Connect apps to payment gateways, social media, or SaaS tools."
      h_line: 1

    - icon: "code"
      name: "Enterprise Solutions"
      text: "Tailored CRM, ERP, or inventory systems. Update outdated systems to modern tech stacks. Design scalable, modular architectures."
      h_line: 1

### Pricing [ pricing ]
pricing:
  title: "Pricing"
  items:
    - icon: "speedometer speed-basic"
      name: "Basic"
      price_pre: "$"
      price: "22"
      price_after: "hour"
      list:
        - text: "Web Development"
          disable: 0
          new: 0

        - text: "Advetising"
          disable: 0
          new: 0

        - text: "Game Development"
          disable: 0
          new: 0

        - text: "Music Writing"
          disable: 1
          new: 0

        - text: "Photography"
          disable: 1
          new: 1
      button_link: "#"
      button_text: "Buy Basic"

    - icon: "speedometer"
      name: "Pro"
      price_pre: "$"
      price: "48"
      price_after: "hour"
      list:
        - text: "Web Development"
          disable: 0
          new: 0

        - text: "Advetising"
          disable: 0
          new: 0

        - text: "Game Development"
          disable: 0
          new: 0

        - text: "Music Writing"
          disable: 0
          new: 0

        - text: "Photography"
          disable: 0
          new: 1
      button_link: "#"
      button_text: "Buy Pro"

### Facts [ facts ]
facts:
  title: "Fun Fact"
  items:
    - icon: "disc"
      name: "80 Albumes Listened"

    - icon: "trophy"
      name: "15 Awards Won"

    - icon: "coffee"
      name: "1 000 Cups of coffee"

    - icon: "flag"
      name: "5 Countries Visited"

### Clients [ clients ]
clients:
  title: "Companies worked with"
  items:
    - url: "https://www.google.com"
      image: "assets/img/clients/client_1.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_2.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_3.png"

    - url: "https://www.google.com"
      image: "assets/img/clients/client_4.png"

### Testimonials [ testimonials ]
testimonials:
  title: "Testimonials"
  items:
    - image: "assets/img/man1.jpg"
      name: "Helen Floyd"
      subname: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/man1.jpg"
      name: "Robert Chase"
      subname: "CEO"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

    - image: "assets/img/man1.jpg"
      name: "Helen Floyd"
      subname: "Art Director"
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit."

### Resume [ resume ]
resume:
  title: "Resume"
  experience:
    title: "Experience"
    icon: "briefcase"
    items:  
      - year: "2022 - Present"
        role: "Software Developer 3"
        company: "Jio Platforms Pvt. Ltd."
        text: "Working on Real-time Speech to Text Systems and creating Batch processing frameworks."
        active: 1
        h_line: 1

      - year: "2020 - 2022"
        role: "Software Developer 2"
        company: "American Express"
        text: "Built Application for KYC Automation of UK and France Market."
        active: 1
        h_line: 1

      - year: "2019 - 2020"
        role: "Software Developer"
        company: "American Express"
        text: "Automation for relevant Ticket generation based on Email classification for around 100 Mailboxes."
        active: 1
        h_line: 0
  education:
    title: "Education"
    icon: "university"
    items:
      - year: "2021 - 2023"
        institution: "Birla Institute of Technology and Science"
        city: "Pilani"
        text: "M. Tech, Software Engineering"
        active: 1
        h_line: 1

      - year: "2015 - 2019"
        institution: "Vellore Institute of Technology"
        city: "Vellore"
        text: "B. Tech, Computer Science"
        active: 1
        h_line: 1

      - year: "2009 - 2014"
        institution: "Delhi Public School"
        city: "Bhopal"
        text: "Scooling till +2"
        active: 1
        h_line: 0

### Skills [ skills ]
skills:
  title: "My Skills"
  columns:

    - type: "dotted" #skills progress type - default, dotted, circles, list
      title: "Languages"
      icon: "flag"
      items:
        - label: "English"
          value: "90" #0-100 progress in %

        - label: "Hindi"
          value: "90" #0-100 progress in %

    - type: "circles" #skills progress type - default, dotted, circles, list
      title: "Coding"
      icon: "code"
      items:
        - label: "Python"
          value: "90" #0-100 progress in %

        - label: "Java"
          value: "75" #0-100 progress in %

        - label: "Docker"
          value: "80" #0-100 progress in %

        - label: "MicroServices"
          value: "95" #0-100 progress in %

    - type: "list" #skills progress type - default, dotted, circles, list
      title: "Knowledge"
      icon: "android-list"
      items:
        - label: "Software Development"
          value: "" #0-100 progress in %

        - label: "Realtime, Batching, Distributed, Enterprise Systems"
          value: "" #0-100 progress in %
        
        - label: "Automated Deployments with CI/CD using Jenkins, Gitlab etc"
          value: "" #0-100 progress in %

        - label: "Containerization using Docker"
          value: "" #0-100 progress in %

        - label: "Kubernetes"
          value: "" #0-100 progress in %

        - label: "Microservice Architecture"
          value: "" #0-100 progress in %

        - label: "API and Integrations with Pipeline Development"
          value: "" #0-100 progress in %

        - label: "Database Management and Migrations"
          value: "" #0-100 progress in %

    - type: "default" #skills progress type - default, dotted, circles, list
      title: "Design"
      icon: "easel"
      items:
        - label: "Web Design"
          value: "90" #0-100 progress in %

        - label: "App Design"
          value: "65" #0-100 progress in %

### Portfolio [ portfolio ]
portfolio:
  title: "Recent Works"
  filters:
    - name: "All"
      slug: "grid-item"
      active: 1

    - name: "Photo"
      slug: "photo"
      active: 0

    - name: "Video"
      slug: "video"
      active: 0

    - name: "Music"
      slug: "music"
      active: 0

    - name: "Design"
      slug: "design"
      active: 0

### Blog [ blog ]
blog:
  title: "Latest Posts"

### Contact Info List [ contacts-info ]
contacts_info:
  title: "Get in Touch"
  list:
    - label: "Current Location"
      value: "Bangalore, India"

    - label: "Email"
      value: "ayushgarg05@gmail.com"

    # - label: "Freelance"
    #   value: "Available"

### Contact Form [ contacts-form ]
contacts_form:
  title: "Contact Form"
